### ISSUE TITLE
Add command line support

### ISSUE THREAD

**Issue by goldenice** [goldenice/Kamele-Framework#6]
Add support for routing over the command line. That would be so awesome: writing command line applications in Kamele. I guess there aren't loads of people who are gonna use this feature, but fuck it, it is mucho awesome.

**Comment by waldirbertazzijr** [comment]
Pretty nice. Reminds me of ruby. So you can fix some stuff without editing anything. Maybe creating controllers and models too?

**Comment by goldenice** [comment]
Just rewrote a tiny bit of the router to support CLI usage, basic routing is now supported. More advanced actions could be implemented in a separate module. (That keeps the system nice and clean too)

Now all that's left is to update the documentation.
