### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by ChrisTerBeke** [goldenice/Kamele-Framework#9]
Support for 3rd party vendors via Composer would be awesome (i.e. use a different template engine or api wrappers for AWS).

**Comment by ChrisTerBeke** [comment]
I know, there is another issue about this, which was closed for some mysterious reason...

**Comment by goldenice** [comment]
That was something I didn't regard as being very useful for the time being, plus I did not have enough time when I closed that issue to develop that. But you're right, this should be implemented somehow.
